COMMENT *PRINTS ERROR MESSAGES*

IF1
	INCLUDE C:\TASM\sudoku\sud_ct.mac	
	INCLUDE C:\TASM\sudoku\sud_io.mac
ENDIF

ERR_DATA SEGMENT PARA PUBLIC 'DATA'
	;Error messages
	ERR_SUCC		DB	'Error: No error$'
	ERR_UNEXP		DB	'Error: Unexpected error$'
	ERR_FOPEN		DB	'Error: The file could not be opened$'
	ERR_FREAD		DB	'Error: The file could not be read$'
	ERR_FORMAT		DB	'Error: Invalid input format$'
	ERR_NOT_SOLVED	DB	'Error: The sudoku could not be solved. Invalid input$'
ERR_DATA ENDS

ERR_CODE SEGMENT PARA PUBLIC 'CODE'	
	ASSUME CS:ERR_CODE,DS:ERR_DATA
	
	PUBLIC	PERROR
	
	;PRINTS AN ERROR MESSAGE FOR THE GIVEN ERROR CODE
	;INPUT: AX - ERROR CODE, DEFINED IN "sud_ct.mac"
	;OUTPUT: -
	PERROR PROC FAR
		PUSH DS
		PUSH AX
		
		PUSH AX
		MOV AX,ERR_DATA
		MOV DS,AX
		POP AX
	
		CMP AX,ESUCC
		JE SUCCESS
		
		CMP AX,EFOPEN
		JE	E_FOPEN
		
		CMP	AX,EFREAD
		JE	E_FREAD
		
		CMP AX,EFORMAT
		JE	FORMAT
		
		CMP AX,ENOSOL
		JE	NO_SOL
		
		PSTRING	ERR_UNEXP
		JMP FINALLY
		
		SUCCESS:
			PSTRING ERR_SUCC
			JMP FINALLY
		E_FOPEN:
			PSTRING ERR_FOPEN
			JMP FINALLY
		E_FREAD:
			PSTRING ERR_FREAD
			JMP FINALLY
		FORMAT:
			PSTRING ERR_FORMAT
			JMP	FINALLY
		NO_SOL:
			PSTRING ERR_NOT_SOLVED
			JMP FINALLY
		
		FINALLY:
		POP AX
		POP DS
		RET
	PERROR ENDP
	
ERR_CODE ENDS

END
